# Form implementation generated from reading ui file 'drawWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DrawWindow(object):
    def setupUi(self, DrawWindow):
        DrawWindow.setObjectName("DrawWindow")
        DrawWindow.resize(631, 439)
        self.centralwidget = QtWidgets.QWidget(parent=DrawWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(0, 0, 75, 24))
        self.pushButton.setObjectName("pushButton")
        self.graphicsView = QtWidgets.QGraphicsView(parent=self.centralwidget)
        self.graphicsView.setGeometry(QtCore.QRect(0, 30, 631, 391))
        self.graphicsView.setObjectName("graphicsView")
        DrawWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=DrawWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 631, 22))
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        self.menuTeste = QtWidgets.QMenu(parent=self.menubar)
        self.menuTeste.setObjectName("menuTeste")
        DrawWindow.setMenuBar(self.menubar)
        self.menubar.addAction(self.menuTeste.menuAction())

        self.retranslateUi(DrawWindow)
        QtCore.QMetaObject.connectSlotsByName(DrawWindow)

    def retranslateUi(self, DrawWindow):
        _translate = QtCore.QCoreApplication.translate
        DrawWindow.setWindowTitle(_translate("DrawWindow", "Draw Window"))
        self.pushButton.setText(_translate("DrawWindow", "Circulo"))
        self.menuTeste.setTitle(_translate("DrawWindow", "Teste"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    DrawWindow = QtWidgets.QMainWindow()
    ui = Ui_DrawWindow()
    ui.setupUi(DrawWindow)
    DrawWindow.show()
    sys.exit(app.exec())
